import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/home/Header";
import ProductContextProvider from "@/context/ProductContextProvider";

export const metadata: Metadata = {
  title: "Raqmee test-1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased overflow-x-clip`}>
        <ProductContextProvider>
          <Header />
          <main>{children}</main>
        </ProductContextProvider>
      </body>
    </html>
  );
}
